types:
  Advanced Industrial Ship Construction:
    CanNotBeTrainedOnTrial: 1
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    Radius: 1.0
    RequiredSkill1: 3392
    RequiredSkill1Level: 2
    RequiredSkill2: 3380
    RequiredSkill2Level: 3
    SecondaryAttribute: 166
    SkillTimeConstant: 3.0
    id: 3396
    marketGroup: 369
    name: Advanced Industrial Ship Construction
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Advanced Industry:
    AdvancedIndustrySkillIndustryJobTimeBonus: -3
    CanNotBeTrainedOnTrial: 1
    PrimaryAttribute: 166
    Radius: 1.0
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 3.0
    id: 3388
    marketGroup: 369
    name: Advanced Industry
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Advanced Large Ship Construction:
    CanNotBeTrainedOnTrial: 1
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    Radius: 1.0
    RequiredSkill1: 3397
    RequiredSkill1Level: 4
    SecondaryAttribute: 166
    SkillTimeConstant: 8.0
    id: 3398
    marketGroup: 369
    name: Advanced Large Ship Construction
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Advanced Mass Production:
    CanNotBeTrainedOnTrial: 1
    ManufacturingSlotBonus: 1
    PrimaryAttribute: 166
    Radius: 1.0
    RequiredSkill1: 3387
    RequiredSkill1Level: 5
    SecondaryAttribute: 165
    SkillTimeConstant: 8.0
    id: 24625
    marketGroup: 369
    name: Advanced Mass Production
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Advanced Medium Ship Construction:
    CanNotBeTrainedOnTrial: 1
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    Radius: 1.0
    RequiredSkill1: 3392
    RequiredSkill1Level: 3
    RequiredSkill2: 3395
    RequiredSkill2Level: 4
    SecondaryAttribute: 166
    SkillTimeConstant: 5.0
    id: 3397
    marketGroup: 369
    name: Advanced Medium Ship Construction
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Advanced Small Ship Construction:
    CanNotBeTrainedOnTrial: 1
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    Radius: 1.0
    RequiredSkill1: 3392
    RequiredSkill1Level: 1
    RequiredSkill2: 3380
    RequiredSkill2Level: 2
    SecondaryAttribute: 166
    SkillTimeConstant: 2.0
    id: 3395
    marketGroup: 369
    name: Advanced Small Ship Construction
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Capital Ship Construction:
    CanNotBeTrainedOnTrial: 1
    PrimaryAttribute: 165
    Radius: 1.0
    RequiredSkill1: 3392
    RequiredSkill1Level: 5
    RequiredSkill2: 3380
    RequiredSkill2Level: 5
    RequiredSkill3: 3388
    RequiredSkill3Level: 5
    SecondaryAttribute: 166
    SkillTimeConstant: 14.0
    id: 22242
    marketGroup: 369
    name: Capital Ship Construction
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Drug Manufacturing:
    CanNotBeTrainedOnTrial: 1
    DurationSkillBonus: 1
    PrimaryAttribute: 166
    Radius: 1.0
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 26224
    marketGroup: 369
    name: Drug Manufacturing
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Industry:
    CanNotBeTrainedOnTrial: 1
    ManufacturingTimeBonus: -4
    PrimaryAttribute: 166
    Radius: 1.0
    SecondaryAttribute: 165
    SkillTimeConstant: 1.0
    id: 3380
    marketGroup: 369
    name: Industry
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Mass Production:
    CanNotBeTrainedOnTrial: 1
    ManufacturingSlotBonus: 1
    PrimaryAttribute: 166
    Radius: 1.0
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3387
    marketGroup: 369
    name: Mass Production
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Outpost Construction:
    CanNotBeTrainedOnTrial: 1
    PrimaryAttribute: 165
    Radius: 1.0
    RequiredSkill1: 3392
    RequiredSkill1Level: 5
    RequiredSkill2: 3380
    RequiredSkill2Level: 5
    RequiredSkill3: 11584
    RequiredSkill3Level: 5
    SecondaryAttribute: 166
    SkillTimeConstant: 16.0
    id: 3400
    marketGroup: 369
    name: Outpost Construction
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
  Supply Chain Management:
    CanNotBeTrainedOnTrial: 1
    PrimaryAttribute: 166
    Radius: 1.0
    RequiredSkill1: 3387
    RequiredSkill1Level: 4
    SecondaryAttribute: 165
    SkillTimeConstant: 3.0
    id: 24268
    marketGroup: 369
    name: Supply Chain Management
    packagedVolume: 0.009999999776482582
    portionSize: 1
    published: true
    volume: 0.009999999776482582
