types:
  Advanced Industrial Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 2
    RequiredSkill2: 3380
    RequiredSkill2Level: 3
    SecondaryAttribute: 166
    SkillTimeConstant: 3.0
    id: 3396
    marketGroup: 369
    name: Advanced Industrial Ship Construction
    price: 2000000.0
    published: true
    volume: 0.01
  Advanced Industry:
    AdvancedIndustrySkillIndustryJobTimeBonus: -3
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 3.0
    id: 3388
    marketGroup: 369
    name: Advanced Industry
    price: 300000.0
    published: true
    volume: 0.01
  Advanced Large Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3397
    RequiredSkill1Level: 4
    SecondaryAttribute: 166
    SkillTimeConstant: 8.0
    id: 3398
    marketGroup: 369
    name: Advanced Large Ship Construction
    price: 3.0E7
    published: true
    volume: 0.01
  Advanced Mass Production:
    CanNotBeTrainedOnTrial: 1
    ManufacturingSlotBonus: 1
    PrimaryAttribute: 166
    RequiredSkill1: 3387
    RequiredSkill1Level: 5
    SecondaryAttribute: 165
    SkillTimeConstant: 8.0
    id: 24625
    marketGroup: 369
    name: Advanced Mass Production
    price: 2.0E7
    published: true
    volume: 0.01
  Advanced Medium Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 3
    RequiredSkill2: 3395
    RequiredSkill2Level: 4
    SecondaryAttribute: 166
    SkillTimeConstant: 5.0
    id: 3397
    marketGroup: 369
    name: Advanced Medium Ship Construction
    price: 1000000.0
    published: true
    volume: 0.01
  Advanced Small Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 1
    RequiredSkill2: 3380
    RequiredSkill2Level: 2
    SecondaryAttribute: 166
    SkillTimeConstant: 2.0
    id: 3395
    marketGroup: 369
    name: Advanced Small Ship Construction
    price: 100000.0
    published: true
    volume: 0.01
  Capital Ship Construction:
    CanNotBeTrainedOnTrial: 1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 5
    RequiredSkill2: 3380
    RequiredSkill2Level: 5
    RequiredSkill3: 3388
    RequiredSkill3Level: 5
    SecondaryAttribute: 166
    SkillTimeConstant: 14.0
    id: 22242
    marketGroup: 369
    name: Capital Ship Construction
    price: 7.5E7
    published: true
    volume: 0.01
  Drug Manufacturing:
    CanNotBeTrainedOnTrial: 1
    DurationSkillBonus: 1
    PrimaryAttribute: 166
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 26224
    marketGroup: 369
    name: Drug Manufacturing
    price: 2.5E7
    published: true
    volume: 0.01
  Industry:
    ManufacturingTimeBonus: -4
    PrimaryAttribute: 166
    SecondaryAttribute: 165
    SkillTimeConstant: 1.0
    id: 3380
    marketGroup: 369
    name: Industry
    price: 30000.0
    published: true
    volume: 0.01
  Mass Production:
    ManufacturingSlotBonus: 1
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3387
    marketGroup: 369
    name: Mass Production
    price: 200000.0
    published: true
    volume: 0.01
  Outpost Construction:
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 5
    RequiredSkill2: 3380
    RequiredSkill2Level: 5
    RequiredSkill3: 11584
    RequiredSkill3Level: 5
    SecondaryAttribute: 166
    SkillTimeConstant: 16.0
    id: 3400
    marketGroup: 369
    name: Outpost Construction
    price: 1.0E8
    published: true
    volume: 0.01
  Supply Chain Management:
    PrimaryAttribute: 166
    RequiredSkill1: 3387
    RequiredSkill1Level: 4
    SecondaryAttribute: 165
    SkillTimeConstant: 3.0
    id: 24268
    marketGroup: 369
    name: Supply Chain Management
    price: 7500000.0
    published: true
    volume: 0.01
