items:
  Dark Matter Field:
    id: 47863
    name: Dark Matter Field
  Electrical Storm:
    id: 47865
    name: Electrical Storm
  Exotic Particle Storm:
    id: 47862
    name: Exotic Particle Storm
  Gamma-Ray Afterglow:
    id: 47866
    name: Gamma-Ray Afterglow
  Plasma Firestorm:
    id: 47864
    name: Plasma Firestorm
