items:
  Background planet Gas:
    id: 47455
    name: Background planet Gas
  Background planet Lava:
    id: 47453
    name: Background planet Lava
  Background planet Moon:
    id: 47451
    name: Background planet Moon
  Background planet Plasma:
    id: 47454
    name: Background planet Plasma
  Background planet Plasma Blood:
    id: 47949
    name: Background planet Plasma Blood
  Background planet Sandstorm:
    id: 47452
    name: Background planet Sandstorm
  Background planet Sandstorm Yellow:
    id: 47950
    name: Background planet Sandstorm Yellow
  Background planet Terestrial:
    id: 47456
    name: Background planet Terestrial
  Effect NPE Vortex:
    id: 42532
    name: Effect NPE Vortex
  TestBackground_01:
    id: 47204
    name: TestBackground_01
  TestBackground_02:
    id: 47205
    name: TestBackground_02
  caustic_toxin_weather_3:
    MaxRange: 2000000
    Untargetable: 1
    WarfareBuff1ID: 99
    WarfareBuff1Value: 70.0
    WarfareBuff2ID: 100
    WarfareBuff2Value: 50.0
    id: 47386
    name: caustic_toxin_weather_3
  darkness_weather_3:
    MaxRange: 2000000
    Untargetable: 1
    WarfareBuff1ID: 97
    WarfareBuff1Value: -70.0
    WarfareBuff2ID: 98
    WarfareBuff2Value: 50.0
    id: 47380
    name: darkness_weather_3
  electric_storm_weather_3:
    MaxRange: 2000000
    Untargetable: 1
    WarfareBuff1ID: 90
    WarfareBuff1Value: 70.0
    WarfareBuff2ID: 92
    WarfareBuff2Value: -50.0
    id: 47383
    name: electric_storm_weather_3
  infernal_weather_3:
    MaxRange: 2000000
    Untargetable: 1
    WarfareBuff1ID: 95
    WarfareBuff1Value: 70.0
    WarfareBuff2ID: 96
    WarfareBuff2Value: 50.0
    id: 47392
    name: infernal_weather_3
  unnamed_gid21177_sid20220:
    id: 36464
    name: unnamed_gid21177_sid20220
  xenon_gas_weather_3:
    MaxRange: 2000000
    Untargetable: 1
    WarfareBuff1ID: 93
    WarfareBuff1Value: 70.0
    WarfareBuff2ID: 94
    WarfareBuff2Value: 50.0
    id: 47389
    name: xenon_gas_weather_3
