types:
  Standup M-Set Missile Precision I:
    CanFitShipGroup01: 1657
    CanFitShipGroup02: 1404
    CanFitShipGroup03: 1406
    HiSecModifier: 1.0
    Hp: 40
    LowSecModifier: 1.2000000476837158
    MaxGroupFitted: 1
    NullSecModifier: 1.2000000476837158
    RequiredSkill1: 26252
    RequiredSkill1Level: 1
    RigSize: 2
    SecurityModifier: 1
    StructureItemVisualFlag: 1
    StructureRigMissileExploVeloBonus: 30
    TechLevel: 1
    UpgradeCost: 100
    id: 37216
    marketGroup: 2344
    mass: 200.0
    name: Standup M-Set Missile Precision I
    published: true
    volume: 10.0
  Standup M-Set Missile Precision II:
    CanFitShipGroup01: 1657
    CanFitShipGroup02: 1404
    CanFitShipGroup03: 1406
    HiSecModifier: 1.0
    Hp: 40
    LowSecModifier: 1.2000000476837158
    MaxGroupFitted: 1
    NullSecModifier: 1.2000000476837158
    RequiredSkill1: 26252
    RequiredSkill1Level: 1
    RigSize: 2
    SecurityModifier: 1
    StructureItemVisualFlag: 1
    StructureRigMissileExploVeloBonus: 35
    TechLevel: 2
    UpgradeCost: 150
    id: 37217
    marketGroup: 2344
    mass: 200.0
    name: Standup M-Set Missile Precision II
    published: true
    volume: 10.0
