items:
  Standup L-Set Point Defense Battery Control I:
    CanFitShipGroup01: 1657
    CanFitShipGroup02: 1404
    CanFitShipGroup03: 1406
    HiSecModifier: 1.0
    Hp: 40
    LowSecModifier: 1.2000000476837158
    MaxGroupFitted: 1
    NullSecModifier: 1.2000000476837158
    RequiredSkill1: 26252
    RequiredSkill1Level: 1
    RigSize: 3
    SecurityModifier: 1
    StructureItemVisualFlag: 1
    StructureRigPDCapUseBonus: -30
    StructureRigPDRangeBonus: 500
    TechLevel: 1
    UpgradeCost: 100
    id: 37258
    marketGroup: 2345
    name: Standup L-Set Point Defense Battery Control I
    published: true
    volume: 20.0
  Standup L-Set Point Defense Battery Control II:
    CanFitShipGroup01: 1657
    CanFitShipGroup02: 1404
    CanFitShipGroup03: 1406
    HiSecModifier: 1.0
    Hp: 40
    LowSecModifier: 1.2000000476837158
    MaxGroupFitted: 1
    NullSecModifier: 1.2000000476837158
    RequiredSkill1: 26252
    RequiredSkill1Level: 1
    RigSize: 3
    SecurityModifier: 1
    StructureItemVisualFlag: 1
    StructureRigPDCapUseBonus: -35
    StructureRigPDRangeBonus: 600
    TechLevel: 2
    UpgradeCost: 150
    id: 37259
    marketGroup: 2345
    name: Standup L-Set Point Defense Battery Control II
    published: true
    volume: 20.0
