items:
  Advanced Industrial Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 2
    RequiredSkill2: 3380
    RequiredSkill2Level: 3
    SecondaryAttribute: 166
    SkillTimeConstant: 3.0
    id: 3396
    name: Advanced Industrial Ship Construction
    volume: 0.01
  Advanced Industry:
    AdvancedIndustrySkillIndustryJobTimeBonus: -3
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 3.0
    id: 3388
    name: Advanced Industry
    volume: 0.01
  Advanced Large Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3397
    RequiredSkill1Level: 4
    SecondaryAttribute: 166
    SkillTimeConstant: 8.0
    id: 3398
    name: Advanced Large Ship Construction
    volume: 0.01
  Advanced Mass Production:
    CanNotBeTrainedOnTrial: 1
    ManufacturingSlotBonus: 1
    PrimaryAttribute: 166
    RequiredSkill1: 3387
    RequiredSkill1Level: 5
    SecondaryAttribute: 165
    SkillTimeConstant: 8.0
    id: 24625
    name: Advanced Mass Production
    volume: 0.01
  Advanced Medium Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 3
    RequiredSkill2: 3395
    RequiredSkill2Level: 4
    SecondaryAttribute: 166
    SkillTimeConstant: 5.0
    id: 3397
    name: Advanced Medium Ship Construction
    volume: 0.01
  Advanced Small Ship Construction:
    ManufactureTimePerLevel: -1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 1
    RequiredSkill2: 3380
    RequiredSkill2Level: 2
    SecondaryAttribute: 166
    SkillTimeConstant: 2.0
    id: 3395
    name: Advanced Small Ship Construction
    volume: 0.01
  Amarr Tech:
    AmarrTechMutator: -5
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3381
    name: Amarr Tech
    volume: 0.01
  Caldari Tech:
    CaldariTechMutator: -5
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3382
    name: Caldari Tech
    volume: 0.01
  Capital Ship Construction:
    CanNotBeTrainedOnTrial: 1
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 5
    RequiredSkill2: 3380
    RequiredSkill2Level: 5
    RequiredSkill3: 3388
    RequiredSkill3Level: 5
    SecondaryAttribute: 166
    SkillTimeConstant: 14.0
    id: 22242
    name: Capital Ship Construction
    volume: 0.01
  Drug Manufacturing:
    CanNotBeTrainedOnTrial: 1
    DurationSkillBonus: 1
    PrimaryAttribute: 166
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 26224
    name: Drug Manufacturing
    volume: 0.01
  Gallente Tech:
    GallenteTechMutator: -5
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3383
    name: Gallente Tech
    volume: 0.01
  Industry:
    ManufacturingTimeBonus: -4
    PrimaryAttribute: 166
    SecondaryAttribute: 165
    SkillTimeConstant: 1.0
    id: 3380
    name: Industry
    volume: 0.01
  Mass Production:
    ManufacturingSlotBonus: 1
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3387
    name: Mass Production
    volume: 0.01
  Minmatar Tech:
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 3
    SecondaryAttribute: 165
    SkillTimeConstant: 2.0
    id: 3384
    name: Minmatar Tech
    volume: 0.01
  Mobile Factory Operation:
    PrimaryAttribute: 166
    RequiredSkill1: 3380
    RequiredSkill1Level: 5
    SecondaryAttribute: 165
    SkillTimeConstant: 5.0
    id: 3391
    name: Mobile Factory Operation
    volume: 0.01
  Outpost Construction:
    PrimaryAttribute: 165
    RequiredSkill1: 3392
    RequiredSkill1Level: 5
    RequiredSkill2: 3380
    RequiredSkill2Level: 5
    RequiredSkill3: 11584
    RequiredSkill3Level: 5
    SecondaryAttribute: 166
    SkillTimeConstant: 16.0
    id: 3400
    name: Outpost Construction
    volume: 0.01
  Supply Chain Management:
    PrimaryAttribute: 166
    RequiredSkill1: 3387
    RequiredSkill1Level: 4
    SecondaryAttribute: 165
    SkillTimeConstant: 3.0
    id: 24268
    name: Supply Chain Management
    volume: 0.01
